//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timotheus.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Timotheus.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add person.
        /// </summary>
        public static string AddConsentForm {
            get {
                return ResourceManager.GetString("AddConsentForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddConsentForm_AddButton {
            get {
                return ResourceManager.GetString("AddConsentForm_AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string AddConsentForm_CancelButton {
            get {
                return ResourceManager.GetString("AddConsentForm_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string AddConsentForm_Comment {
            get {
                return ResourceManager.GetString("AddConsentForm_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string AddConsentForm_Date {
            get {
                return ResourceManager.GetString("AddConsentForm_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name cannot be empty.
        /// </summary>
        public static string AddConsentForm_EmptyName {
            get {
                return ResourceManager.GetString("AddConsentForm_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An empty version field is interpreted as no consent. Are you sure you want to add the person?.
        /// </summary>
        public static string AddConsentForm_EmptyVersion {
            get {
                return ResourceManager.GetString("AddConsentForm_EmptyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AddConsentForm_Name {
            get {
                return ResourceManager.GetString("AddConsentForm_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string AddConsentForm_Version {
            get {
                return ResourceManager.GetString("AddConsentForm_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add event.
        /// </summary>
        public static string AddEvent {
            get {
                return ResourceManager.GetString("AddEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddEvent_AddButton {
            get {
                return ResourceManager.GetString("AddEvent_AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All day event.
        /// </summary>
        public static string AddEvent_AllDayBox {
            get {
                return ResourceManager.GetString("AddEvent_AllDayBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string AddEvent_CancelButton {
            get {
                return ResourceManager.GetString("AddEvent_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrip..
        /// </summary>
        public static string AddEvent_DescriptionLabel {
            get {
                return ResourceManager.GetString("AddEvent_DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit event.
        /// </summary>
        public static string AddEvent_Edit {
            get {
                return ResourceManager.GetString("AddEvent_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string AddEvent_EditButton {
            get {
                return ResourceManager.GetString("AddEvent_EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End*.
        /// </summary>
        public static string AddEvent_EndLabel {
            get {
                return ResourceManager.GetString("AddEvent_EndLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string AddEvent_LocationLabel {
            get {
                return ResourceManager.GetString("AddEvent_LocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name*.
        /// </summary>
        public static string AddEvent_NameLabel {
            get {
                return ResourceManager.GetString("AddEvent_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start*.
        /// </summary>
        public static string AddEvent_StartLabel {
            get {
                return ResourceManager.GetString("AddEvent_StartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Event.
        /// </summary>
        public static string Calendar_AddButton {
            get {
                return ResourceManager.GetString("Calendar_AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an event to the calendar.
        /// </summary>
        public static string Calendar_AddEvent_ToolTip {
            get {
                return ResourceManager.GetString("Calendar_AddEvent_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Calendar_All {
            get {
                return ResourceManager.GetString("Calendar_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Calendar_AllButton {
            get {
                return ResourceManager.GetString("Calendar_AllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back in time.
        /// </summary>
        public static string Calendar_BackTime_ToolTip {
            get {
                return ResourceManager.GetString("Calendar_BackTime_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the event &quot;#&quot;?.
        /// </summary>
        public static string Calendar_DeleteEvent {
            get {
                return ResourceManager.GetString("Calendar_DeleteEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Calendar_DescriptionColumn {
            get {
                return ResourceManager.GetString("Calendar_DescriptionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string Calendar_EndColumn {
            get {
                return ResourceManager.GetString("Calendar_EndColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports the calendar as PDF, and only shows events in the current period..
        /// </summary>
        public static string Calendar_Export_ToolTip {
            get {
                return ResourceManager.GetString("Calendar_Export_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Calendar_ExportButton {
            get {
                return ResourceManager.GetString("Calendar_ExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fall.
        /// </summary>
        public static string Calendar_Fall {
            get {
                return ResourceManager.GetString("Calendar_Fall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go forward in time.
        /// </summary>
        public static string Calendar_ForwardTime_ToolTip {
            get {
                return ResourceManager.GetString("Calendar_ForwardTime_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half-year.
        /// </summary>
        public static string Calendar_HalfYearButton {
            get {
                return ResourceManager.GetString("Calendar_HalfYearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Calendar_LocationColumn {
            get {
                return ResourceManager.GetString("Calendar_LocationColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Calendar_MonthButton {
            get {
                return ResourceManager.GetString("Calendar_MonthButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Calendar_NameColumn {
            get {
                return ResourceManager.GetString("Calendar_NameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a calendar.
        /// </summary>
        public static string Calendar_Open_ToolTip {
            get {
                return ResourceManager.GetString("Calendar_Open_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string Calendar_Page {
            get {
                return ResourceManager.GetString("Calendar_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current period. The calendar will only show events in this period..
        /// </summary>
        public static string Calendar_PeriodBox_ToolTip {
            get {
                return ResourceManager.GetString("Calendar_PeriodBox_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current type of period..
        /// </summary>
        public static string Calendar_PeriodType_ToolTip {
            get {
                return ResourceManager.GetString("Calendar_PeriodType_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the calendar as a .ics file. This does NOT synchronize the calendar..
        /// </summary>
        public static string Calendar_Save_ToolTip {
            get {
                return ResourceManager.GetString("Calendar_Save_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spring.
        /// </summary>
        public static string Calendar_Spring {
            get {
                return ResourceManager.GetString("Calendar_Spring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Calendar_StartColumn {
            get {
                return ResourceManager.GetString("Calendar_StartColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize the calendar with a remote calendar.
        /// </summary>
        public static string Calendar_Sync_ToolTip {
            get {
                return ResourceManager.GetString("Calendar_Sync_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize.
        /// </summary>
        public static string Calendar_SyncButton {
            get {
                return ResourceManager.GetString("Calendar_SyncButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Calendar_YearButton {
            get {
                return ResourceManager.GetString("Calendar_YearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditKeyDialog {
            get {
                return ResourceManager.GetString("EditKeyDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add standard keys.
        /// </summary>
        public static string EditKeyDialog_AddStdButton {
            get {
                return ResourceManager.GetString("EditKeyDialog_AddStdButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string EditKeyDialog_CancelButton {
            get {
                return ResourceManager.GetString("EditKeyDialog_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string EditKeyDialog_OKButton {
            get {
                return ResourceManager.GetString("EditKeyDialog_OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program is already running. If you can&apos;t see it, check the system tray or task manager.
        /// </summary>
        public static string Exception_AlreadyRunning {
            get {
                return ResourceManager.GetString("Exception_AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t go further back. This is the root directory..
        /// </summary>
        public static string Exception_CantGoUpDirectory {
            get {
                return ResourceManager.GetString("Exception_CantGoUpDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address cannot be empty.
        /// </summary>
        public static string Exception_EmptyAddress {
            get {
                return ResourceManager.GetString("Exception_EmptyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICS field cannot be empty.
        /// </summary>
        public static string Exception_EmptyICS {
            get {
                return ResourceManager.GetString("Exception_EmptyICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be empty.
        /// </summary>
        public static string Exception_EmptyName {
            get {
                return ResourceManager.GetString("Exception_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date cannot be before the start date..
        /// </summary>
        public static string Exception_EndBeforeStart {
            get {
                return ResourceManager.GetString("Exception_EndBeforeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The local folder couldn&apos;t be found. Do you want to find a new folder for syncing?.
        /// </summary>
        public static string Exception_FolderNotFound {
            get {
                return ResourceManager.GetString("Exception_FolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image couldn&apos;t be found. Choose another..
        /// </summary>
        public static string Exception_ImageNotFound {
            get {
                return ResourceManager.GetString("Exception_ImageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar isn&apos;t formatted correctly.
        /// </summary>
        public static string Exception_InvalidCalendar {
            get {
                return ResourceManager.GetString("Exception_InvalidCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This was not a valid event..
        /// </summary>
        public static string Exception_InvalidEvent {
            get {
                return ResourceManager.GetString("Exception_InvalidEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        /// </summary>
        public static string Exception_InvalidInput {
            get {
                return ResourceManager.GetString("Exception_InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an invalid password. Try another....
        /// </summary>
        public static string Exception_InvalidPassword {
            get {
                return ResourceManager.GetString("Exception_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t load file.
        /// </summary>
        public static string Exception_LoadFailed {
            get {
                return ResourceManager.GetString("Exception_LoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Exception_Message {
            get {
                return ResourceManager.GetString("Exception_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Exception_Name {
            get {
                return ResourceManager.GetString("Exception_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection to the internet could not be established. Check your internet conneciton or firewall..
        /// </summary>
        public static string Exception_NoInternet {
            get {
                return ResourceManager.GetString("Exception_NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key file could not be loaded.
        /// </summary>
        public static string Exception_NoKeys {
            get {
                return ResourceManager.GetString("Exception_NoKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive could not be found. Try choosing another folder in &quot;Export&quot;..
        /// </summary>
        public static string Exception_PDFArchiveNotFound {
            get {
                return ResourceManager.GetString("Exception_PDFArchiveNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The export path cannot be empty..
        /// </summary>
        public static string Exception_PDFEmptyExport {
            get {
                return ResourceManager.GetString("Exception_PDFEmptyExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File saved!.
        /// </summary>
        public static string Exception_SaveSuccessful {
            get {
                return ResourceManager.GetString("Exception_SaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t save file.
        /// </summary>
        public static string Exception_Saving {
            get {
                return ResourceManager.GetString("Exception_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is not in the directory.
        /// </summary>
        public static string Exception_SFTPInvalidPath {
            get {
                return ResourceManager.GetString("Exception_SFTPInvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t sync the calendar.
        /// </summary>
        public static string Exception_Sync {
            get {
                return ResourceManager.GetString("Exception_Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t sync the files.
        /// </summary>
        public static string Exception_SyncSFTP {
            get {
                return ResourceManager.GetString("Exception_SyncSFTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to quit? There is unsaved progress..
        /// </summary>
        public static string Exception_UnsavedProgress {
            get {
                return ResourceManager.GetString("Exception_UnsavedProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Exception_Warning {
            get {
                return ResourceManager.GetString("Exception_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password.
        /// </summary>
        public static string Exception_WrongPassword {
            get {
                return ResourceManager.GetString("Exception_WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timotheus is a program which seeks to help assocations with their calendar, file sharing, and hopefully a lot more in the future!.
        /// </summary>
        public static string FirstTime_1P {
            get {
                return ResourceManager.GetString("FirstTime_1P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program uses a key file (.tkey) to connect all these services by storing usernames, passwords etc. in a encrypted file..
        /// </summary>
        public static string FirstTime_2P {
            get {
                return ResourceManager.GetString("FirstTime_2P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do you want to start?.
        /// </summary>
        public static string FirstTime_3P {
            get {
                return ResourceManager.GetString("FirstTime_3P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string FirstTime_Welcome {
            get {
                return ResourceManager.GetString("FirstTime_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With key.
        /// </summary>
        public static string FirstTime_With {
            get {
                return ResourceManager.GetString("FirstTime_With", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without key.
        /// </summary>
        public static string FirstTime_Without {
            get {
                return ResourceManager.GetString("FirstTime_Without", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Help_Close {
            get {
                return ResourceManager.GetString("Help_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors:.
        /// </summary>
        public static string Help_ContributorsLabel {
            get {
                return ResourceManager.GetString("Help_ContributorsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string Help_EmailLabel {
            get {
                return ResourceManager.GetString("Help_EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License:.
        /// </summary>
        public static string Help_LicenseLabel {
            get {
                return ResourceManager.GetString("Help_LicenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source:.
        /// </summary>
        public static string Help_SourceLabel {
            get {
                return ResourceManager.GetString("Help_SourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string Help_VersionLabel {
            get {
                return ResourceManager.GetString("Help_VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes detected.
        /// </summary>
        public static string InsertKey_ChangeDetected {
            get {
                return ResourceManager.GetString("InsertKey_ChangeDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserting key.
        /// </summary>
        public static string InsertKey_Dialog {
            get {
                return ResourceManager.GetString("InsertKey_Dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the changes made to the key?.
        /// </summary>
        public static string InsertKey_DoYouWantToSave {
            get {
                return ResourceManager.GetString("InsertKey_DoYouWantToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening calendar.
        /// </summary>
        public static string InsertKey_LoadCalendar {
            get {
                return ResourceManager.GetString("InsertKey_LoadCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to remote directory.
        /// </summary>
        public static string InsertKey_LoadFiles {
            get {
                return ResourceManager.GetString("InsertKey_LoadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading people.
        /// </summary>
        public static string InsertKey_LoadPeople {
            get {
                return ResourceManager.GetString("InsertKey_LoadPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string OpenCalendar {
            get {
                return ResourceManager.GetString("OpenCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string OpenCalendar_BrowseButton {
            get {
                return ResourceManager.GetString("OpenCalendar_BrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote.
        /// </summary>
        public static string OpenCalendar_CalDAVButton {
            get {
                return ResourceManager.GetString("OpenCalendar_CalDAVButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string OpenCalendar_CancelButton {
            get {
                return ResourceManager.GetString("OpenCalendar_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string OpenCalendar_ICSButton {
            get {
                return ResourceManager.GetString("OpenCalendar_ICSButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string OpenCalendar_ICSLabel {
            get {
                return ResourceManager.GetString("OpenCalendar_ICSLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string OpenCalendar_OpenButton {
            get {
                return ResourceManager.GetString("OpenCalendar_OpenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string OpenCalendar_PasswordLabel {
            get {
                return ResourceManager.GetString("OpenCalendar_PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string OpenCalendar_URLLabel {
            get {
                return ResourceManager.GetString("OpenCalendar_URLLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string OpenCalendar_UsernameLabel {
            get {
                return ResourceManager.GetString("OpenCalendar_UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password required.
        /// </summary>
        public static string PasswordDialog {
            get {
                return ResourceManager.GetString("PasswordDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string PasswordDialog_CancelButton {
            get {
                return ResourceManager.GetString("PasswordDialog_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordDialog_Label {
            get {
                return ResourceManager.GetString("PasswordDialog_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string PasswordDialog_OKButton {
            get {
                return ResourceManager.GetString("PasswordDialog_OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save password.
        /// </summary>
        public static string PasswordDialog_SaveBox {
            get {
                return ResourceManager.GetString("PasswordDialog_SaveBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export PDF.
        /// </summary>
        public static string PDF {
            get {
                return ResourceManager.GetString("PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string PDF_Activity {
            get {
                return ResourceManager.GetString("PDF_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        public static string PDF_ArchivePath {
            get {
                return ResourceManager.GetString("PDF_ArchivePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backpage.
        /// </summary>
        public static string PDF_Backpage {
            get {
                return ResourceManager.GetString("PDF_Backpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string PDF_Browse {
            get {
                return ResourceManager.GetString("PDF_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string PDF_Cancel {
            get {
                return ResourceManager.GetString("PDF_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffee.
        /// </summary>
        public static string PDF_Coffee {
            get {
                return ResourceManager.GetString("PDF_Coffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string PDF_Comment {
            get {
                return ResourceManager.GetString("PDF_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string PDF_Date {
            get {
                return ResourceManager.GetString("PDF_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string PDF_ExportPath {
            get {
                return ResourceManager.GetString("PDF_ExportPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer.
        /// </summary>
        public static string PDF_Footer {
            get {
                return ResourceManager.GetString("PDF_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader.
        /// </summary>
        public static string PDF_Leader {
            get {
                return ResourceManager.GetString("PDF_Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string PDF_Logo {
            get {
                return ResourceManager.GetString("PDF_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musician.
        /// </summary>
        public static string PDF_Musician {
            get {
                return ResourceManager.GetString("PDF_Musician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string PDF_Ok {
            get {
                return ResourceManager.GetString("PDF_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule for.
        /// </summary>
        public static string PDF_Schedule {
            get {
                return ResourceManager.GetString("PDF_Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string PDF_Start {
            get {
                return ResourceManager.GetString("PDF_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle.
        /// </summary>
        public static string PDF_Subtitle {
            get {
                return ResourceManager.GetString("PDF_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string PDF_Title {
            get {
                return ResourceManager.GetString("PDF_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        public static string PDF_Type_Book {
            get {
                return ResourceManager.GetString("PDF_Type_Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string PDF_Type_Table {
            get {
                return ResourceManager.GetString("PDF_Type_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to.
        /// </summary>
        public static string PDF_Welcome {
            get {
                return ResourceManager.GetString("PDF_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string People_Active {
            get {
                return ResourceManager.GetString("People_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make the person active/inactive.
        /// </summary>
        public static string People_Active_ToolTip {
            get {
                return ResourceManager.GetString("People_Active_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add person.
        /// </summary>
        public static string People_Add {
            get {
                return ResourceManager.GetString("People_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add person.
        /// </summary>
        public static string People_Add_ToolTip {
            get {
                return ResourceManager.GetString("People_Add_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string People_Comment {
            get {
                return ResourceManager.GetString("People_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string People_ConsentDate {
            get {
                return ResourceManager.GetString("People_ConsentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string People_ConsentVersion {
            get {
                return ResourceManager.GetString("People_ConsentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &quot;#&quot;?.
        /// </summary>
        public static string People_Delete {
            get {
                return ResourceManager.GetString("People_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the person.
        /// </summary>
        public static string People_Delete_ToolTip {
            get {
                return ResourceManager.GetString("People_Delete_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide inactive.
        /// </summary>
        public static string People_HideInactive {
            get {
                return ResourceManager.GetString("People_HideInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string People_InActive {
            get {
                return ResourceManager.GetString("People_InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string People_Name {
            get {
                return ResourceManager.GetString("People_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a file with people.
        /// </summary>
        public static string People_Open_ToolTip {
            get {
                return ResourceManager.GetString("People_Open_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consent forms.
        /// </summary>
        public static string People_Page {
            get {
                return ResourceManager.GetString("People_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the people to a file.
        /// </summary>
        public static string People_Save_ToolTip {
            get {
                return ResourceManager.GetString("People_Save_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string People_Search {
            get {
                return ResourceManager.GetString("People_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in the peoples names and comments.
        /// </summary>
        public static string People_Search_ToolTip {
            get {
                return ResourceManager.GetString("People_Search_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide/show people who are inactive.
        /// </summary>
        public static string People_ShowHide_ToolTip {
            get {
                return ResourceManager.GetString("People_ShowHide_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show inactive.
        /// </summary>
        public static string People_ShowInactive {
            get {
                return ResourceManager.GetString("People_ShowInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Settings_AddressLabel {
            get {
                return ResourceManager.GetString("Settings_AddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Settings_BrowseButton {
            get {
                return ResourceManager.GetString("Settings_BrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete program settings.
        /// </summary>
        public static string Settings_DeleteSettings {
            get {
                return ResourceManager.GetString("Settings_DeleteSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event settings.
        /// </summary>
        public static string Settings_Event {
            get {
                return ResourceManager.GetString("Settings_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Settings_EventDescription {
            get {
                return ResourceManager.GetString("Settings_EventDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string Settings_EventEnd {
            get {
                return ResourceManager.GetString("Settings_EventEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Settings_EventStart {
            get {
                return ResourceManager.GetString("Settings_EventStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Settings_EventTime {
            get {
                return ResourceManager.GetString("Settings_EventTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association information.
        /// </summary>
        public static string Settings_InfoBox {
            get {
                return ResourceManager.GetString("Settings_InfoBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish.
        /// </summary>
        public static string Settings_Language_Danish {
            get {
                return ResourceManager.GetString("Settings_Language_Danish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Settings_Language_English {
            get {
                return ResourceManager.GetString("Settings_Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the program to change the language of the program.
        /// </summary>
        public static string Settings_LanguageChanged {
            get {
                return ResourceManager.GetString("Settings_LanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Settings_LogoLabel {
            get {
                return ResourceManager.GetString("Settings_LogoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look for updates.
        /// </summary>
        public static string Settings_LookForUpdates {
            get {
                return ResourceManager.GetString("Settings_LookForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Settings_NameLabel {
            get {
                return ResourceManager.GetString("Settings_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program settings.
        /// </summary>
        public static string Settings_Program {
            get {
                return ResourceManager.GetString("Settings_Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes need to be uploaded.
        /// </summary>
        public static string SFTP_ChangedLocal {
            get {
                return ResourceManager.GetString("SFTP_ChangedLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes need to be downloaded.
        /// </summary>
        public static string SFTP_ChangedRemote {
            get {
                return ResourceManager.GetString("SFTP_ChangedRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to make &quot;#1&quot; #2 with immediate effect? It is currently #3..
        /// </summary>
        public static string SFTP_ChangePermission {
            get {
                return ResourceManager.GetString("SFTP_ChangePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string SFTP_ContextMenu_Delete {
            get {
                return ResourceManager.GetString("SFTP_ContextMenu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New folder.
        /// </summary>
        public static string SFTP_ContextMenu_NewFolder {
            get {
                return ResourceManager.GetString("SFTP_ContextMenu_NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string SFTP_ContextMenu_Open {
            get {
                return ResourceManager.GetString("SFTP_ContextMenu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make private.
        /// </summary>
        public static string SFTP_ContextMenu_Private {
            get {
                return ResourceManager.GetString("SFTP_ContextMenu_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make public.
        /// </summary>
        public static string SFTP_ContextMenu_Public {
            get {
                return ResourceManager.GetString("SFTP_ContextMenu_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string SFTP_ContextMenu_Rename {
            get {
                return ResourceManager.GetString("SFTP_ContextMenu_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in file explorer.
        /// </summary>
        public static string SFTP_ContextMenu_ShowInExplorer {
            get {
                return ResourceManager.GetString("SFTP_ContextMenu_ShowInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize file.
        /// </summary>
        public static string SFTP_ContextMenu_Sync {
            get {
                return ResourceManager.GetString("SFTP_ContextMenu_Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes the file locally and remotely.
        /// </summary>
        public static string SFTP_Delete_ToolTip {
            get {
                return ResourceManager.GetString("SFTP_Delete_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted on computer.
        /// </summary>
        public static string SFTP_DeleteLocal {
            get {
                return ResourceManager.GetString("SFTP_DeleteLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted on server.
        /// </summary>
        public static string SFTP_DeleteRemote {
            get {
                return ResourceManager.GetString("SFTP_DeleteRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &quot;#&quot; locally and remotely?.
        /// </summary>
        public static string SFTP_DeleteWarning {
            get {
                return ResourceManager.GetString("SFTP_DeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A folder with that name already exists..
        /// </summary>
        public static string SFTP_FolderExists {
            get {
                return ResourceManager.GetString("SFTP_FolderExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back to the last folder.
        /// </summary>
        public static string SFTP_GoUp_ToolTip {
            get {
                return ResourceManager.GetString("SFTP_GoUp_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string SFTP_GoUpButton {
            get {
                return ResourceManager.GetString("SFTP_GoUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing.
        /// </summary>
        public static string SFTP_Message {
            get {
                return ResourceManager.GetString("SFTP_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string SFTP_NameColumn {
            get {
                return ResourceManager.GetString("SFTP_NameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New folder.
        /// </summary>
        public static string SFTP_NewFolder {
            get {
                return ResourceManager.GetString("SFTP_NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new folder.
        /// </summary>
        public static string SFTP_NewFolder_ToolTip {
            get {
                return ResourceManager.GetString("SFTP_NewFolder_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs to be uploaded.
        /// </summary>
        public static string SFTP_NewLocal {
            get {
                return ResourceManager.GetString("SFTP_NewLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs to be downloaded.
        /// </summary>
        public static string SFTP_NewRemote {
            get {
                return ResourceManager.GetString("SFTP_NewRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the file. If it is a directory, then the files in the directory are shown..
        /// </summary>
        public static string SFTP_Open_ToolTip {
            get {
                return ResourceManager.GetString("SFTP_Open_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string SFTP_Page {
            get {
                return ResourceManager.GetString("SFTP_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current folder path.
        /// </summary>
        public static string SFTP_Path_ToolTip {
            get {
                return ResourceManager.GetString("SFTP_Path_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change permission.
        /// </summary>
        public static string SFTP_Permission_ToolTip {
            get {
                return ResourceManager.GetString("SFTP_Permission_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string SFTP_Private {
            get {
                return ResourceManager.GetString("SFTP_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string SFTP_Public {
            get {
                return ResourceManager.GetString("SFTP_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh the folder and look for updates.
        /// </summary>
        public static string SFTP_Refresh_ToolTip {
            get {
                return ResourceManager.GetString("SFTP_Refresh_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup which folder to synchronize with.
        /// </summary>
        public static string SFTP_Setup_ToolTip {
            get {
                return ResourceManager.GetString("SFTP_Setup_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string SFTP_SetupButton {
            get {
                return ResourceManager.GetString("SFTP_SetupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the file on the computer..
        /// </summary>
        public static string SFTP_ShowInExplorer_ToolTip {
            get {
                return ResourceManager.GetString("SFTP_ShowInExplorer_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size.
        /// </summary>
        public static string SFTP_SizeColumn {
            get {
                return ResourceManager.GetString("SFTP_SizeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize all files and folders.
        /// </summary>
        public static string SFTP_Sync_ToolTip {
            get {
                return ResourceManager.GetString("SFTP_Sync_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize.
        /// </summary>
        public static string SFTP_SyncButton {
            get {
                return ResourceManager.GetString("SFTP_SyncButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizes the file.
        /// </summary>
        public static string SFTP_SyncFile_ToolTip {
            get {
                return ResourceManager.GetString("SFTP_SyncFile_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing folders.
        /// </summary>
        public static string SFTP_SyncWorker {
            get {
                return ResourceManager.GetString("SFTP_SyncWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string SFTP_UpdateButton {
            get {
                return ResourceManager.GetString("SFTP_UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string SFTPSetup {
            get {
                return ResourceManager.GetString("SFTPSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string SFTPSetup_BrowseButton {
            get {
                return ResourceManager.GetString("SFTPSetup_BrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SFTPSetup_CancelButton {
            get {
                return ResourceManager.GetString("SFTPSetup_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string SFTPSetup_HostLabel {
            get {
                return ResourceManager.GetString("SFTPSetup_HostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string SFTPSetup_LocalDirectoryLabel {
            get {
                return ResourceManager.GetString("SFTPSetup_LocalDirectoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string SFTPSetup_PasswordLabel {
            get {
                return ResourceManager.GetString("SFTPSetup_PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string SFTPSetup_PortLabel {
            get {
                return ResourceManager.GetString("SFTPSetup_PortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote.
        /// </summary>
        public static string SFTPSetup_RemoteDirectoryLabel {
            get {
                return ResourceManager.GetString("SFTPSetup_RemoteDirectoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string SFTPSetup_SetupButton {
            get {
                return ResourceManager.GetString("SFTPSetup_SetupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string SFTPSetup_UsernameLabel {
            get {
                return ResourceManager.GetString("SFTPSetup_UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize.
        /// </summary>
        public static string SyncCalendar {
            get {
                return ResourceManager.GetString("SyncCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string SyncCalendar_CalDAVLabel {
            get {
                return ResourceManager.GetString("SyncCalendar_CalDAVLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SyncCalendar_CancelButton {
            get {
                return ResourceManager.GetString("SyncCalendar_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync custom period.
        /// </summary>
        public static string SyncCalendar_CustomCalendarButton {
            get {
                return ResourceManager.GetString("SyncCalendar_CustomCalendarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string SyncCalendar_Destination {
            get {
                return ResourceManager.GetString("SyncCalendar_Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync the entire calendar.
        /// </summary>
        public static string SyncCalendar_EntireCalendarButton {
            get {
                return ResourceManager.GetString("SyncCalendar_EntireCalendarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another calendar.
        /// </summary>
        public static string SyncCalendar_NewCalendarButton {
            get {
                return ResourceManager.GetString("SyncCalendar_NewCalendarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string SyncCalendar_PasswordLabel {
            get {
                return ResourceManager.GetString("SyncCalendar_PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync the period.
        /// </summary>
        public static string SyncCalendar_PeriodCalendarButton {
            get {
                return ResourceManager.GetString("SyncCalendar_PeriodCalendarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SyncCalendar_Settings {
            get {
                return ResourceManager.GetString("SyncCalendar_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        public static string SyncCalendar_SyncButton {
            get {
                return ResourceManager.GetString("SyncCalendar_SyncButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current calendar.
        /// </summary>
        public static string SyncCalendar_UseExistingButton {
            get {
                return ResourceManager.GetString("SyncCalendar_UseExistingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string SyncCalendar_UsernameLabel {
            get {
                return ResourceManager.GetString("SyncCalendar_UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing calendar.
        /// </summary>
        public static string SyncCalendar_Worker {
            get {
                return ResourceManager.GetString("SyncCalendar_Worker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string TextDialog {
            get {
                return ResourceManager.GetString("TextDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ToolStrip_EditKey {
            get {
                return ResourceManager.GetString("ToolStrip_EditKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make changes to the current key.
        /// </summary>
        public static string ToolStrip_EditKey_ToolTip {
            get {
                return ResourceManager.GetString("ToolStrip_EditKey_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ToolStrip_Exit {
            get {
                return ResourceManager.GetString("ToolStrip_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string ToolStrip_File {
            get {
                return ResourceManager.GetString("ToolStrip_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string ToolStrip_Help {
            get {
                return ResourceManager.GetString("ToolStrip_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find information about the program.
        /// </summary>
        public static string ToolStrip_Help_ToolTip {
            get {
                return ResourceManager.GetString("ToolStrip_Help_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string ToolStrip_Key {
            get {
                return ResourceManager.GetString("ToolStrip_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string ToolStrip_LoadKey {
            get {
                return ResourceManager.GetString("ToolStrip_LoadKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string ToolStrip_NewFile {
            get {
                return ResourceManager.GetString("ToolStrip_NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new project.
        /// </summary>
        public static string ToolStrip_NewFile_ToolTip {
            get {
                return ResourceManager.GetString("ToolStrip_NewFile_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to create a new project? Unsaved progress will be lost..
        /// </summary>
        public static string ToolStrip_NewSecure {
            get {
                return ResourceManager.GetString("ToolStrip_NewSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string ToolStrip_OpenFile {
            get {
                return ResourceManager.GetString("ToolStrip_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a key and open it.
        /// </summary>
        public static string ToolStrip_OpenKey_ToolTip {
            get {
                return ResourceManager.GetString("ToolStrip_OpenKey_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        public static string ToolStrip_SaveAsKey {
            get {
                return ResourceManager.GetString("ToolStrip_SaveAsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save a copy of the current key to a specific location.
        /// </summary>
        public static string ToolStrip_SaveAsKey_ToolTip {
            get {
                return ResourceManager.GetString("ToolStrip_SaveAsKey_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ToolStrip_SaveFile {
            get {
                return ResourceManager.GetString("ToolStrip_SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ToolStrip_SaveKey {
            get {
                return ResourceManager.GetString("ToolStrip_SaveKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the current key.
        /// </summary>
        public static string ToolStrip_SaveKey_ToolTip {
            get {
                return ResourceManager.GetString("ToolStrip_SaveKey_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can change the settings of the program.
        /// </summary>
        public static string ToolStrip_Settings_ToolTip {
            get {
                return ResourceManager.GetString("ToolStrip_Settings_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new update (#) available on the website: www.mjrj.dk.
        /// </summary>
        public static string UpdateDialog_Text {
            get {
                return ResourceManager.GetString("UpdateDialog_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateDialog_Title {
            get {
                return ResourceManager.GetString("UpdateDialog_Title", resourceCulture);
            }
        }
    }
}
