//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timotheus.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Timotheus.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddEvent {
            get {
                return ResourceManager.GetString("AddEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddEvent_AddButton {
            get {
                return ResourceManager.GetString("AddEvent_AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All day event.
        /// </summary>
        public static string AddEvent_AllDayBox {
            get {
                return ResourceManager.GetString("AddEvent_AllDayBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string AddEvent_CancelButton {
            get {
                return ResourceManager.GetString("AddEvent_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrip..
        /// </summary>
        public static string AddEvent_DescriptionLabel {
            get {
                return ResourceManager.GetString("AddEvent_DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End*.
        /// </summary>
        public static string AddEvent_EndLabel {
            get {
                return ResourceManager.GetString("AddEvent_EndLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string AddEvent_LocationLabel {
            get {
                return ResourceManager.GetString("AddEvent_LocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name*.
        /// </summary>
        public static string AddEvent_NameLabel {
            get {
                return ResourceManager.GetString("AddEvent_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start*.
        /// </summary>
        public static string AddEvent_StartLabel {
            get {
                return ResourceManager.GetString("AddEvent_StartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Event.
        /// </summary>
        public static string Calendar_AddButton {
            get {
                return ResourceManager.GetString("Calendar_AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Calendar_All {
            get {
                return ResourceManager.GetString("Calendar_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Calendar_AllButton {
            get {
                return ResourceManager.GetString("Calendar_AllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string Calendar_April {
            get {
                return ResourceManager.GetString("Calendar_April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string Calendar_August {
            get {
                return ResourceManager.GetString("Calendar_August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string Calendar_December {
            get {
                return ResourceManager.GetString("Calendar_December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Calendar_DescriptionColumn {
            get {
                return ResourceManager.GetString("Calendar_DescriptionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string Calendar_EndColumn {
            get {
                return ResourceManager.GetString("Calendar_EndColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export PDF.
        /// </summary>
        public static string Calendar_ExportButton {
            get {
                return ResourceManager.GetString("Calendar_ExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fall.
        /// </summary>
        public static string Calendar_Fall {
            get {
                return ResourceManager.GetString("Calendar_Fall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string Calendar_February {
            get {
                return ResourceManager.GetString("Calendar_February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half-year.
        /// </summary>
        public static string Calendar_HalfYearButton {
            get {
                return ResourceManager.GetString("Calendar_HalfYearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string Calendar_January {
            get {
                return ResourceManager.GetString("Calendar_January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string Calendar_July {
            get {
                return ResourceManager.GetString("Calendar_July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string Calendar_June {
            get {
                return ResourceManager.GetString("Calendar_June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Calendar_LocationColumn {
            get {
                return ResourceManager.GetString("Calendar_LocationColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string Calendar_March {
            get {
                return ResourceManager.GetString("Calendar_March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string Calendar_May {
            get {
                return ResourceManager.GetString("Calendar_May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Calendar_MonthButton {
            get {
                return ResourceManager.GetString("Calendar_MonthButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Calendar_NameColumn {
            get {
                return ResourceManager.GetString("Calendar_NameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string Calendar_November {
            get {
                return ResourceManager.GetString("Calendar_November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string Calendar_October {
            get {
                return ResourceManager.GetString("Calendar_October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string Calendar_Page {
            get {
                return ResourceManager.GetString("Calendar_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string Calendar_September {
            get {
                return ResourceManager.GetString("Calendar_September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spring.
        /// </summary>
        public static string Calendar_Spring {
            get {
                return ResourceManager.GetString("Calendar_Spring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Calendar_StartColumn {
            get {
                return ResourceManager.GetString("Calendar_StartColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize.
        /// </summary>
        public static string Calendar_SyncButton {
            get {
                return ResourceManager.GetString("Calendar_SyncButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Calendar_YearButton {
            get {
                return ResourceManager.GetString("Calendar_YearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditKeyDialog {
            get {
                return ResourceManager.GetString("EditKeyDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add standard keys.
        /// </summary>
        public static string EditKeyDialog_AddStdButton {
            get {
                return ResourceManager.GetString("EditKeyDialog_AddStdButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string EditKeyDialog_CancelButton {
            get {
                return ResourceManager.GetString("EditKeyDialog_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string EditKeyDialog_OKButton {
            get {
                return ResourceManager.GetString("EditKeyDialog_OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program is already running. If you can&apos;t see it, check the system tray or task manager.
        /// </summary>
        public static string Exception_AlreadyRunning {
            get {
                return ResourceManager.GetString("Exception_AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address cannot be empty.
        /// </summary>
        public static string Exception_EmptyAddress {
            get {
                return ResourceManager.GetString("Exception_EmptyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICS field cannot be empty.
        /// </summary>
        public static string Exception_EmptyICS {
            get {
                return ResourceManager.GetString("Exception_EmptyICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be empty.
        /// </summary>
        public static string Exception_EmptyName {
            get {
                return ResourceManager.GetString("Exception_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar isn&apos;t formatted correctly.
        /// </summary>
        public static string Exception_InvalidCalendar {
            get {
                return ResourceManager.GetString("Exception_InvalidCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        /// </summary>
        public static string Exception_InvalidInput {
            get {
                return ResourceManager.GetString("Exception_InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an invalid password. Try another....
        /// </summary>
        public static string Exception_InvalidPassword {
            get {
                return ResourceManager.GetString("Exception_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t load file.
        /// </summary>
        public static string Exception_LoadFailed {
            get {
                return ResourceManager.GetString("Exception_LoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Exception_Name {
            get {
                return ResourceManager.GetString("Exception_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key file could not be loaded.
        /// </summary>
        public static string Exception_NoKeys {
            get {
                return ResourceManager.GetString("Exception_NoKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t save file.
        /// </summary>
        public static string Exception_Saving {
            get {
                return ResourceManager.GetString("Exception_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is not in the directory.
        /// </summary>
        public static string Exception_SFTPInvalidPath {
            get {
                return ResourceManager.GetString("Exception_SFTPInvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t sync the calendar.
        /// </summary>
        public static string Exception_Sync {
            get {
                return ResourceManager.GetString("Exception_Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t sync the files.
        /// </summary>
        public static string Exception_SyncSFTP {
            get {
                return ResourceManager.GetString("Exception_SyncSFTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password.
        /// </summary>
        public static string Exception_WrongPassword {
            get {
                return ResourceManager.GetString("Exception_WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Help_Close {
            get {
                return ResourceManager.GetString("Help_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors:.
        /// </summary>
        public static string Help_ContributorsLabel {
            get {
                return ResourceManager.GetString("Help_ContributorsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string Help_EmailLabel {
            get {
                return ResourceManager.GetString("Help_EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License:.
        /// </summary>
        public static string Help_LicenseLabel {
            get {
                return ResourceManager.GetString("Help_LicenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source:.
        /// </summary>
        public static string Help_SourceLabel {
            get {
                return ResourceManager.GetString("Help_SourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string Help_VersionLabel {
            get {
                return ResourceManager.GetString("Help_VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string OpenCalendar {
            get {
                return ResourceManager.GetString("OpenCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string OpenCalendar_BrowseButton {
            get {
                return ResourceManager.GetString("OpenCalendar_BrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote.
        /// </summary>
        public static string OpenCalendar_CalDAVButton {
            get {
                return ResourceManager.GetString("OpenCalendar_CalDAVButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string OpenCalendar_CancelButton {
            get {
                return ResourceManager.GetString("OpenCalendar_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string OpenCalendar_ICSButton {
            get {
                return ResourceManager.GetString("OpenCalendar_ICSButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string OpenCalendar_ICSLabel {
            get {
                return ResourceManager.GetString("OpenCalendar_ICSLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string OpenCalendar_OpenButton {
            get {
                return ResourceManager.GetString("OpenCalendar_OpenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string OpenCalendar_PasswordLabel {
            get {
                return ResourceManager.GetString("OpenCalendar_PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string OpenCalendar_URLLabel {
            get {
                return ResourceManager.GetString("OpenCalendar_URLLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string OpenCalendar_UsernameLabel {
            get {
                return ResourceManager.GetString("OpenCalendar_UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password required.
        /// </summary>
        public static string PasswordDialog {
            get {
                return ResourceManager.GetString("PasswordDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string PasswordDialog_CancelButton {
            get {
                return ResourceManager.GetString("PasswordDialog_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordDialog_Label {
            get {
                return ResourceManager.GetString("PasswordDialog_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string PasswordDialog_OKButton {
            get {
                return ResourceManager.GetString("PasswordDialog_OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save password.
        /// </summary>
        public static string PasswordDialog_SaveBox {
            get {
                return ResourceManager.GetString("PasswordDialog_SaveBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string PDF_Activity {
            get {
                return ResourceManager.GetString("PDF_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffee.
        /// </summary>
        public static string PDF_Coffee {
            get {
                return ResourceManager.GetString("PDF_Coffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string PDF_Date {
            get {
                return ResourceManager.GetString("PDF_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader.
        /// </summary>
        public static string PDF_Leader {
            get {
                return ResourceManager.GetString("PDF_Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musician.
        /// </summary>
        public static string PDF_Musician {
            get {
                return ResourceManager.GetString("PDF_Musician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule for.
        /// </summary>
        public static string PDF_Schedule {
            get {
                return ResourceManager.GetString("PDF_Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string PDF_Start {
            get {
                return ResourceManager.GetString("PDF_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to.
        /// </summary>
        public static string PDF_Welcome {
            get {
                return ResourceManager.GetString("PDF_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Settings_AddressLabel {
            get {
                return ResourceManager.GetString("Settings_AddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Settings_BrowseButton {
            get {
                return ResourceManager.GetString("Settings_BrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Settings_LogoLabel {
            get {
                return ResourceManager.GetString("Settings_LogoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Settings_NameLabel {
            get {
                return ResourceManager.GetString("Settings_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Page {
            get {
                return ResourceManager.GetString("Settings_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association information.
        /// </summary>
        public static string Settins_InfoBox {
            get {
                return ResourceManager.GetString("Settins_InfoBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string SFTP_GoUpButton {
            get {
                return ResourceManager.GetString("SFTP_GoUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string SFTP_NameColumn {
            get {
                return ResourceManager.GetString("SFTP_NameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string SFTP_Page {
            get {
                return ResourceManager.GetString("SFTP_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string SFTP_SetupButton {
            get {
                return ResourceManager.GetString("SFTP_SetupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size.
        /// </summary>
        public static string SFTP_SizeColumn {
            get {
                return ResourceManager.GetString("SFTP_SizeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize.
        /// </summary>
        public static string SFTP_SyncButton {
            get {
                return ResourceManager.GetString("SFTP_SyncButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string SFTPSetup {
            get {
                return ResourceManager.GetString("SFTPSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string SFTPSetup_BrowseButton {
            get {
                return ResourceManager.GetString("SFTPSetup_BrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SFTPSetup_CancelButton {
            get {
                return ResourceManager.GetString("SFTPSetup_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string SFTPSetup_HostLabel {
            get {
                return ResourceManager.GetString("SFTPSetup_HostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string SFTPSetup_LocalDirectoryLabel {
            get {
                return ResourceManager.GetString("SFTPSetup_LocalDirectoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string SFTPSetup_PasswordLabel {
            get {
                return ResourceManager.GetString("SFTPSetup_PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote.
        /// </summary>
        public static string SFTPSetup_RemoteDirectoryLabel {
            get {
                return ResourceManager.GetString("SFTPSetup_RemoteDirectoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string SFTPSetup_SetupButton {
            get {
                return ResourceManager.GetString("SFTPSetup_SetupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string SFTPSetup_UsernameLabel {
            get {
                return ResourceManager.GetString("SFTPSetup_UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize.
        /// </summary>
        public static string SyncCalendar {
            get {
                return ResourceManager.GetString("SyncCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string SyncCalendar_CalDAVLabel {
            get {
                return ResourceManager.GetString("SyncCalendar_CalDAVLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SyncCalendar_CancelButton {
            get {
                return ResourceManager.GetString("SyncCalendar_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync custom period.
        /// </summary>
        public static string SyncCalendar_CustomCalendarButton {
            get {
                return ResourceManager.GetString("SyncCalendar_CustomCalendarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string SyncCalendar_Destination {
            get {
                return ResourceManager.GetString("SyncCalendar_Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync the entire calendar.
        /// </summary>
        public static string SyncCalendar_EntireCalendarButton {
            get {
                return ResourceManager.GetString("SyncCalendar_EntireCalendarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another calendar.
        /// </summary>
        public static string SyncCalendar_NewCalendarButton {
            get {
                return ResourceManager.GetString("SyncCalendar_NewCalendarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string SyncCalendar_PasswordLabel {
            get {
                return ResourceManager.GetString("SyncCalendar_PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync the period.
        /// </summary>
        public static string SyncCalendar_PeriodCalendarButton {
            get {
                return ResourceManager.GetString("SyncCalendar_PeriodCalendarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SyncCalendar_Settings {
            get {
                return ResourceManager.GetString("SyncCalendar_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        public static string SyncCalendar_SyncButton {
            get {
                return ResourceManager.GetString("SyncCalendar_SyncButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current calendar.
        /// </summary>
        public static string SyncCalendar_UseExistingButton {
            get {
                return ResourceManager.GetString("SyncCalendar_UseExistingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string SyncCalendar_UsernameLabel {
            get {
                return ResourceManager.GetString("SyncCalendar_UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit key.
        /// </summary>
        public static string ToolStrip_EditKey {
            get {
                return ResourceManager.GetString("ToolStrip_EditKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ToolStrip_Exit {
            get {
                return ResourceManager.GetString("ToolStrip_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string ToolStrip_File {
            get {
                return ResourceManager.GetString("ToolStrip_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string ToolStrip_Help {
            get {
                return ResourceManager.GetString("ToolStrip_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string ToolStrip_Key {
            get {
                return ResourceManager.GetString("ToolStrip_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open key.
        /// </summary>
        public static string ToolStrip_LoadKey {
            get {
                return ResourceManager.GetString("ToolStrip_LoadKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string ToolStrip_NewFile {
            get {
                return ResourceManager.GetString("ToolStrip_NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to create a new project? Unsaved progress will be lost..
        /// </summary>
        public static string ToolStrip_NewSecure {
            get {
                return ResourceManager.GetString("ToolStrip_NewSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string ToolStrip_OpenFile {
            get {
                return ResourceManager.GetString("ToolStrip_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ToolStrip_SaveFile {
            get {
                return ResourceManager.GetString("ToolStrip_SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save key.
        /// </summary>
        public static string ToolStrip_SaveKey {
            get {
                return ResourceManager.GetString("ToolStrip_SaveKey", resourceCulture);
            }
        }
    }
}
